### ISSUE TITLE
Create index.html File

### ISSUE THREAD

**Issue by hussain-alhassan** [rumailah-devs/vacancy#1]
Hi @saleh-alhassan,

Please create an index.html file. This file should have a basic html5 code with an empty div inside the body tag.

To do this, please follow these steps:

1- Create a new branch named "feature/add-index-file"
2- Create the index.html file.

3- **Add** your file to the Staging area.
4- **Commit** your changes. Let's use a commit message like "Added index.html file".
5- **Push** your changes to your branch (not to master).

Then, create a **Pull Request** from your branch. Mention me & @KhalafMH as the reviewers.
We will review your code and either approve it or add some comments.

Please (try first), then let me know if you need some help.

**Comment by hussain-alhassan** [comment]
This issue can be closed. It's done in this pull request #5

**Comment by saleh-alhassan** [comment]
DONE
