### ISSUE TITLE
Create app.css File

### ISSUE THREAD

**Issue by hussain-alhassan** [rumailah-devs/vacancy#2]
Hi @Skillful0,

Please create an app.css file. If #1 is not finished yet, then assume there is an index file (you can create one).
The index file has a starting html code with a div inside the body.

You should make the background color of that div "green". You can do this by adding a "class" to the div in the html file and then change the background in the app.css file. If you're not sure, please follow this tutorial
https://www.w3schools.com/tags/tag_div.ASP

To submit your code, please follow these steps:
1- Create a new branch named "feature/add-style-file"
2- Create the app.css file.

3- **Add** your file to the Staging area.
4- **Commit** your changes. Let's use a commit message like "Added app.css file".
5- **Push** your changes to your branch.

Then, create a **Pull Request** from your branch. Mention me & @KhalafMH as the reviewers.
We will review your code and either approve it or add some comments.

Please (try first), then let me know if you need some help.

**Comment by kazemalhassan** [comment]
Done..

**Comment by hussain-alhassan** [comment]
> Done..

@kazemalhassan , this is not done yet. Can you please Reopen it?

**Comment by salam1416** [comment]
Is there anything still needed for this task?

**Comment by hussain-alhassan** [comment]
> Is there anything still needed for this task?

The **index** file has a starting html code with a div inside the body.

You should **make the background color of that div "green"**. You can do this by adding a "class" to the div in the html file and then change the background in the app.css file. If you're not sure, please follow this tutorial

**Comment by kazemalhassan** [comment]
Done..
