### ISSUE TITLE
Create admin.html File

### ISSUE THREAD

**Issue by hussain-alhassan** [rumailah-devs/vacancy#3]
Hi @kazemalhassan ,

Please create an admin.html file. This file should have a basic html5 code with 2 divs inside it.
One div has a red background, and the other one has a green background. If #2 is not complete, then create an app.css file to put the background code for the 2 divs in it.

To do this, please follow these steps:

1- Create a new branch named "feature/add-admin-file"
2- Create the admin.html file.

3- **Add** your file to the Staging area.
4- **Commit** your changes. Let's use a commit message like "Added admin.html file".
5- **Push** your changes to your branch.

Then, create a Pull Request from your branch. Mention me & @KhalafMH as the reviewers.
We will review your code and either approve it or add some comments.

Please (try first), then let me know if you need some help.

**Comment by kazemalhassan** [comment]
Done..
